### ISSUE TITLE
Error when running testnet

### ISSUE THREAD

**Issue by dmus** [jarmstrong2/handwritingnet#1]
When running th testNet.lua the following error occurs:
`unknown Torch class <nn.MixtureCriterion>`

What could be the issue?

**Comment by jarmstrong2** [comment]
Can you post the full error so I know where the problem is originating?

**Comment by jarmstrong2** [comment]
@dmus the class is actually here mixtureCriterionMat.lua, so maybe add a requires to testnet.lua for that file.

**Comment by dmus** [comment]
Yes, you are right. That require solves that error.
