### ISSUE TITLE
Error when running testnet:invalid arguments

### ISSUE THREAD

**Issue by dmus** [jarmstrong2/handwritingnet#2]
I get the following error when I try to run testNet.lua. I added the line require 'cunn' to the script.

/home/derkmus/torch/install/bin/luajit: /home/derkmus/torch/install/share/lua/5.1/nn/Linear.lua:66: invalid arguments: CudaTensor number CudaTensor number FloatTensor CudaTensor 
expected arguments: _CudaTensor~2D_ [CudaTensor~2D] [float] CudaTensor~2D CudaTensor~2D | _CudaTensor~2D_ float [CudaTensor~2D] float CudaTensor~2D CudaTensor~2D
stack traceback:
    [C]: in function 'addmm'
    /home/derkmus/torch/install/share/lua/5.1/nn/Linear.lua:66: in function 'func'
    .../derkmus/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
    .../derkmus/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'func'
    .../derkmus/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
    .../derkmus/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
    testNet.lua:108: in main chunk
    [C]: in function 'dofile'
    ...kmus/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

**Comment by jarmstrong2** [comment]
This was made so that ppl without GPUs could run it. You're welcome to try to replace the *_nocuda requires with their CUDA alternates (i.e. just *) and see if it works. I'm not actively maintaining this repo just so you know.

**Comment by dmus** [comment]
Yes did that, but the error message stays the same
